[package]
name = "echo_server"
version = "0.1.0"
edition = "2021"

[dependencies]
net_framework = {path = "../tools/net_framework"}
clap = { version = "4.5.9", features = ["derive"] }
simplelog = "0.12.2"
anyhow = "1.0.86"
ntest = "0.9.3"